import type { ReactNode } from "react";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { NewConversationLink } from "@/components/new-conversation-link";
import { Wordmark } from "@/components/wordmark";
import { languageName, textDirection } from "@/lib/languages";
import { scenarioLabel } from "@/lib/scenarios";
import type {
  Correction,
  ReachedFor,
  SavedWordOutcome,
  Suggestion,
} from "@/lib/analysis";
import { createClient, currentUser } from "@/lib/supabase/server";
import type { Turn } from "../actions";
import { RecordingSection } from "./recording-section";
import { ReviewRunner } from "./review-runner";
import { SaveWordButton } from "./save-word-button";

// The review is generated by a server action on this page, and a slow model
// can take a while on a long conversation.
export const maxDuration = 60;

export default async function AnalysisPage({
  params,
}: PageProps<"/conversation/[id]/analysis">) {
  const { id } = await params;

  const supabase = await createClient();
  const user = await currentUser(supabase);

  if (!user) redirect("/login");

  const { data: session, error } = await supabase
    .from("sessions")
    .select(
      "id, target_language, scenario, started_at, ended_at, transcript, agent_session_id",
    )
    .eq("id", id)
    .single();

  // PGRST116 is "no rows": a genuinely missing (or someone else's) session.
  // Anything else is a real failure and should not masquerade as a 404.
  if (error && error.code !== "PGRST116") throw new Error(error.message);
  if (!session) notFound();

  const transcript = (session.transcript ?? []) as Turn[];
  const direction = textDirection(session.target_language);
  const spokenTurns = transcript.filter((turn) => turn.role === "user").length;

  const [{ data: analysis }, { data: vocabulary }] = await Promise.all([
    supabase
      .from("session_analysis")
      .select(
        "grammar_notes, vocab_used, vocab_forgotten, vocab_suggested, fluency_notes, summary_text, strengths, next_steps",
      )
      .eq("session_id", session.id)
      .maybeSingle(),
    supabase
      .from("vocabulary_items")
      .select("text")
      .eq("target_language", session.target_language),
  ]);

  const savedWords = new Set(
    (vocabulary ?? []).map((item) => item.text.trim().toLowerCase()),
  );

  return (
    <main className="flex flex-1 flex-col">
      {/* Sticky, so a new conversation is reachable from anywhere in a long
          transcript. */}
      <header className="sticky top-0 z-10 border-b border-border/60 bg-background/90 backdrop-blur">
        <div className="mx-auto flex w-full max-w-2xl items-center justify-between px-6 py-4">
          <Link href="/dashboard">
            <Wordmark />
          </Link>
          <div className="flex items-center gap-5">
            <Link
              href="/dashboard"
              className="text-sm font-medium text-muted transition-colors hover:text-foreground"
            >
              Dashboard
            </Link>
            <NewConversationLink />
          </div>
        </div>
      </header>

      <div className="mx-auto w-full max-w-2xl px-6 pt-8 pb-24">
        <p className="text-sm font-medium text-muted">
          {scenarioLabel(session.scenario) ?? "Free conversation"} ·{" "}
          {languageName(session.target_language)}
        </p>
        <h1 className="mt-2 text-[32px] leading-tight font-bold tracking-[-0.02em]">
          {spokenTurns > 0
            ? `You spoke ${spokenTurns} ${spokenTurns === 1 ? "time" : "times"}`
            : "That one stayed quiet"}
        </h1>

        <div className="mt-8">
          <RecordingSection
            sessionId={session.id}
            hasRecording={Boolean(session.agent_session_id)}
          />
        </div>

        {analysis ? (
          <Review
            sessionId={session.id}
            direction={direction}
            summary={analysis.summary_text}
            strengths={analysis.strengths}
            nextSteps={analysis.next_steps}
            corrections={analysis.grammar_notes as Correction[]}
            reachedFor={analysis.vocab_forgotten as ReachedFor[]}
            suggestions={analysis.vocab_suggested as Suggestion[]}
            savedUsed={analysis.vocab_used as SavedWordOutcome[]}
            fluencyNotes={analysis.fluency_notes as string[]}
            savedWords={savedWords}
          />
        ) : spokenTurns > 0 ? (
          <div className="mt-6">
            <ReviewRunner sessionId={session.id} />
          </div>
        ) : null}

        {transcript.length > 0 ? (
          <div className="mt-10">
            <h2 className="text-[17px] font-semibold tracking-[-0.01em]">
              Transcript
            </h2>
            <div className="mt-5 flex flex-col gap-5" dir={direction}>
              {transcript.map((turn, index) =>
                turn.role === "agent" ? (
                  <div key={index} className="flex flex-col gap-2">
                    <span className="text-[9px] font-bold tracking-[0.18em] text-accent">
                      VOCES
                    </span>
                    <p className="text-[16px] leading-relaxed">{turn.text}</p>
                    {turn.translation && (
                      <p dir="auto" className="text-[13px] leading-relaxed text-muted/70">
                        {turn.translation}
                      </p>
                    )}
                  </div>
                ) : (
                  <div key={index} className="flex flex-col items-end gap-1.5">
                    <p className="max-w-[80%] rounded-2xl border border-border bg-surface px-4 py-3 text-[16px] leading-relaxed text-muted">
                      {turn.text}
                    </p>
                    {turn.translation && (
                      <p dir="auto" className="max-w-[80%] px-1 text-[13px] leading-relaxed text-muted/70">
                        {turn.translation}
                      </p>
                    )}
                  </div>
                ),
              )}
            </div>
          </div>
        ) : (
          <p className="mt-10 text-sm leading-relaxed text-muted">
            Nothing was said in this one.
          </p>
        )}

        <Link
          href="/conversation/new"
          className="mt-12 inline-block rounded-full bg-accent px-7 py-4 text-base font-semibold text-white transition-colors hover:bg-accent-hover"
        >
          Start another conversation
        </Link>
      </div>
    </main>
  );
}

function SectionHeading({ children }: { children: ReactNode }) {
  return (
    <h2 className="text-[17px] font-semibold tracking-[-0.01em]">{children}</h2>
  );
}

function Review({
  sessionId,
  direction,
  summary,
  strengths,
  nextSteps,
  corrections,
  reachedFor,
  suggestions,
  savedUsed,
  fluencyNotes,
  savedWords,
}: {
  sessionId: string;
  direction: "ltr" | "rtl";
  summary: string | null;
  strengths: string | null;
  nextSteps: string | null;
  corrections: Correction[];
  reachedFor: ReachedFor[];
  suggestions: Suggestion[];
  savedUsed: SavedWordOutcome[];
  fluencyNotes: string[];
  savedWords: Set<string>;
}) {
  const used = savedUsed.filter((word) => word.outcome === "used");
  const struggled = savedUsed.filter((word) => word.outcome === "struggled");

  return (
    <div className="mt-6 flex flex-col gap-10">
      <div className="rounded-2xl border border-border bg-surface p-6">
        {summary && <p className="text-[15px] leading-relaxed">{summary}</p>}
        {strengths && (
          <p className="mt-4 text-[14px] leading-relaxed text-muted">
            <span className="font-semibold text-foreground">Went well: </span>
            {strengths}
          </p>
        )}
        {nextSteps && (
          <p className="mt-2 text-[14px] leading-relaxed text-muted">
            <span className="font-semibold text-foreground">Next time: </span>
            {nextSteps}
          </p>
        )}
        {fluencyNotes.length > 0 && (
          <ul className="mt-4 flex list-disc flex-col gap-1 pl-5 text-[14px] leading-relaxed text-muted">
            {fluencyNotes.map((note, index) => (
              <li key={index}>{note}</li>
            ))}
          </ul>
        )}
      </div>

      <section>
        <SectionHeading>Corrections</SectionHeading>
        {corrections.length > 0 ? (
          <ul className="mt-5 flex flex-col gap-4">
            {corrections.map((correction, index) => (
              <li
                key={index}
                className="rounded-2xl border border-border bg-surface p-5"
              >
                <div className="flex flex-wrap items-center gap-2">
                  {correction.category && (
                    <span className="text-[11px] font-semibold tracking-wide text-muted uppercase">
                      {correction.category}
                    </span>
                  )}
                  {correction.recurring && (
                    <span className="rounded-full bg-accent-soft px-2.5 py-0.5 text-[11px] font-semibold text-accent">
                      Came up before
                    </span>
                  )}
                </div>
                <div dir={direction} className="mt-3 flex flex-col gap-1">
                  <p className="text-[15px] text-muted line-through decoration-muted/60">
                    {correction.original}
                  </p>
                  <p className="text-[16px] font-medium">{correction.corrected}</p>
                </div>
                {correction.explanation && (
                  <p className="mt-3 text-[14px] leading-relaxed text-muted">
                    {correction.explanation}
                  </p>
                )}
              </li>
            ))}
          </ul>
        ) : (
          <p className="mt-3 text-[14px] leading-relaxed text-muted">
            No grammar slips worth flagging this time.
          </p>
        )}
      </section>

      {reachedFor.length > 0 && (
        <section>
          <SectionHeading>Words you reached for</SectionHeading>
          <p className="mt-2 text-[14px] leading-relaxed text-muted">
            Added to your{" "}
            <Link href="/vocabulary" className="text-accent hover:underline">
              vocabulary
            </Link>
            , so they come up again in your next conversations.
          </p>
          <ul className="mt-4 flex flex-col">
            {reachedFor.map((word, index) => (
              <li
                key={index}
                className="flex flex-col gap-1 border-b border-border py-3 last:border-0"
              >
                <div className="flex items-baseline justify-between gap-4">
                  <span dir={direction} className="text-[16px] font-medium">
                    {word.text}
                  </span>
                  <span className="text-right text-[14px] text-muted">
                    {word.translation}
                  </span>
                </div>
                {word.context && (
                  <span dir="auto" className="text-[13px] text-muted/80 italic">
                    &ldquo;{word.context}&rdquo;
                  </span>
                )}
              </li>
            ))}
          </ul>
        </section>
      )}

      {suggestions.length > 0 && (
        <section>
          <SectionHeading>Worth adding</SectionHeading>
          <ul className="mt-4 flex flex-col">
            {suggestions.map((word, index) => (
              <li
                key={index}
                className="flex items-center justify-between gap-4 border-b border-border py-3 last:border-0"
              >
                <div className="flex flex-col gap-1">
                  <div className="flex flex-wrap items-baseline gap-x-3">
                    <span dir={direction} className="text-[16px] font-medium">
                      {word.text}
                    </span>
                    <span className="text-[14px] text-muted">
                      {word.translation}
                    </span>
                  </div>
                  {word.example && (
                    <span dir={direction} className="text-[13px] text-muted/80">
                      {word.example}
                    </span>
                  )}
                </div>
                <SaveWordButton
                  sessionId={sessionId}
                  word={word}
                  saved={savedWords.has(word.text.trim().toLowerCase())}
                />
              </li>
            ))}
          </ul>
        </section>
      )}

      {(used.length > 0 || struggled.length > 0) && (
        <section>
          <SectionHeading>Your saved words</SectionHeading>
          <div className="mt-4 flex flex-wrap gap-2" dir={direction}>
            {used.map((word) => (
              <span
                key={`used-${word.text}`}
                className="rounded-full bg-accent-soft px-3 py-1 text-[13px] font-medium text-accent"
              >
                ✓ {word.text}
              </span>
            ))}
            {struggled.map((word) => (
              <span
                key={`struggled-${word.text}`}
                className="rounded-full border border-border px-3 py-1 text-[13px] font-medium text-muted"
              >
                {word.text}
              </span>
            ))}
          </div>
          {struggled.length > 0 && (
            <p className="mt-3 text-[13px] text-muted">
              Outlined words were tricky this time; they&apos;ll come up again.
            </p>
          )}
        </section>
      )}
    </div>
  );
}
