import type { CSSProperties, ReactNode } from "react";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Landmark } from "@/components/landmarks";
import { PronounceButton } from "@/components/pronounce-button";
import type {
  Correction,
  ReachedFor,
  SavedWordOutcome,
  Suggestion,
} from "@/lib/analysis";
import { languageName, textDirection } from "@/lib/languages";
import { scenarioLabel } from "@/lib/scenarios";
import { createClient, currentUser } from "@/lib/supabase/server";
import type { Turn } from "../actions";
import { RecordingSection } from "./recording-section";
import { ReportTabs } from "./report-tabs";
import { ReviewRunner } from "./review-runner";
import { SaveWordButton } from "./save-word-button";

// The review is generated by a server action on this page, and a slow model
// can take a while on a long conversation.
export const maxDuration = 60;

const ACCENT = "#DE5E1C";

function words(text: string) {
  return text.split(/\s+/).filter(Boolean).length;
}

function Ring({
  percent,
  color,
  track,
  label,
}: {
  percent: number | null;
  color: string;
  track: string;
  label: string;
}) {
  const r = 40.5;
  const circumference = 2 * Math.PI * r;
  const filled = percent === null ? 0 : (circumference * Math.min(100, percent)) / 100;
  return (
    <span className="relative block size-[88px] shrink-0 sm:size-[132px]">
      {/* By night the pastel track would glare, so it is mixed from the
          ring's own colour instead. */}
      <svg
        viewBox="0 0 88 88"
        className="size-full"
        style={{ "--track": track, "--ring": color } as CSSProperties}
        aria-hidden
      >
        <circle
          cx="44"
          cy="44"
          r={r}
          fill="none"
          strokeWidth="7"
          className="stroke-(--track) dark:stroke-[color-mix(in_srgb,var(--ring)_26%,transparent)]"
        />
        {filled > 0 && (
          <circle
            cx="44"
            cy="44"
            r={r}
            fill="none"
            stroke={color}
            strokeWidth="7"
            strokeLinecap="round"
            strokeDasharray={`${filled} ${circumference}`}
            transform="rotate(-90 44 44)"
          />
        )}
      </svg>
      <span
        className="absolute inset-0 grid place-items-center text-[19px] font-bold sm:text-[28px]"
        style={{ color }}
      >
        {label}
      </span>
    </span>
  );
}

function ScoreCard({
  title,
  caption,
  children,
}: {
  title: string;
  caption: string;
  children: ReactNode;
}) {
  return (
    <div className="flex flex-1 flex-col items-center rounded-2xl border border-line bg-card px-2 pt-3.5 pb-4 text-center sm:rounded-[18px] sm:pt-[22px] sm:pb-6">
      <span className="text-[14px] font-semibold sm:text-[17px]">{title}</span>
      <span className="mt-0.5 min-h-[2lh] text-[11.5px] leading-tight text-mute sm:mt-1 sm:min-h-0 sm:text-[14px]">
        {caption}
      </span>
      <span className="mt-2.5 sm:mt-4">{children}</span>
    </div>
  );
}

function Takeaway({ icon, title, body }: { icon: ReactNode; title: string; body: string }) {
  return (
    <div className="flex flex-1 items-center gap-3.5 rounded-[14px] border border-line bg-card px-3.5 py-3 sm:flex-col sm:items-start sm:gap-3 sm:rounded-2xl sm:p-5">
      <span className="grid size-9 shrink-0 place-items-center rounded-[11px] bg-tint sm:size-11 sm:rounded-[13px]">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke={ACCENT} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
          {icon}
        </svg>
      </span>
      <span className="flex flex-col gap-1">
        <span className="text-[14px] font-semibold sm:text-[16px]">{title}</span>
        <span className="text-[12.5px] leading-snug text-mute sm:text-[13.5px]">{body}</span>
      </span>
    </div>
  );
}

function SessionThumb({ code }: { code: string }) {
  return (
    <svg viewBox="0 0 64 64" className="size-16 shrink-0 rounded-xl sm:size-[68px] sm:rounded-[14px]" aria-hidden>
      <defs>
        <linearGradient id="session-thumb" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor="#3D4A5C" />
          <stop offset="0.5" stopColor="#9A6440" />
          <stop offset="1" stopColor="#3A2313" />
        </linearGradient>
      </defs>
      <rect width="64" height="64" fill="url(#session-thumb)" />
      <g style={{ filter: "brightness(0.85)" }}>
        <Landmark code={code} x={6} baseline={58} scale={0.14} />
      </g>
      <rect y="56" width="64" height="8" fill="#241609" />
    </svg>
  );
}

export default async function AnalysisPage({
  params,
}: PageProps<"/conversation/[id]/analysis">) {
  const { id } = await params;

  const supabase = await createClient();
  const user = await currentUser(supabase);

  if (!user) redirect("/login");

  const { data: session, error } = await supabase
    .from("sessions")
    .select(
      "id, target_language, scenario, started_at, ended_at, transcript, agent_session_id",
    )
    .eq("id", id)
    .single();

  // PGRST116 is "no rows": a genuinely missing (or someone else's) session.
  // Anything else is a real failure and should not masquerade as a 404.
  if (error && error.code !== "PGRST116") throw new Error(error.message);
  if (!session) notFound();

  const transcript = (session.transcript ?? []) as Turn[];
  const direction = textDirection(session.target_language);
  const learnerTurns = transcript.filter((turn) => turn.role === "user");
  const spokenTurns = learnerTurns.length;
  const language = languageName(session.target_language) ?? session.target_language;
  const minutes = session.ended_at
    ? Math.max(
        1,
        Math.round(
          (new Date(session.ended_at).getTime() - new Date(session.started_at).getTime()) /
            60_000,
        ),
      )
    : null;

  const [{ data: analysis }, { data: vocabulary }] = await Promise.all([
    supabase
      .from("session_analysis")
      .select(
        "grammar_notes, vocab_used, vocab_forgotten, vocab_suggested, fluency_notes, summary_text, strengths, next_steps",
      )
      .eq("session_id", session.id)
      .maybeSingle(),
    supabase
      .from("vocabulary_items")
      .select("text")
      .eq("target_language", session.target_language),
  ]);

  const savedWords = new Set(
    (vocabulary ?? []).map((item) => item.text.trim().toLowerCase()),
  );

  const corrections = (analysis?.grammar_notes ?? []) as Correction[];
  const reachedFor = (analysis?.vocab_forgotten ?? []) as ReachedFor[];
  const suggestions = (analysis?.vocab_suggested ?? []) as Suggestion[];
  const savedUsed = (analysis?.vocab_used ?? []) as SavedWordOutcome[];
  const fluencyNotes = (analysis?.fluency_notes ?? []) as string[];

  // Every score is measured from this conversation. The design's
  // pronunciation score has nothing behind it, so vocabulary takes its place.
  const learnerWords = learnerTurns.reduce((sum, turn) => sum + words(turn.text), 0);
  const allWords = transcript.reduce((sum, turn) => sum + words(turn.text), 0);
  const speakingShare = allWords ? Math.round((100 * learnerWords) / allWords) : 0;
  const grammarScore =
    analysis && spokenTurns
      ? Math.round(100 * Math.max(0, 1 - corrections.length / spokenTurns))
      : null;

  const categories = new Map<string, number>();
  for (const correction of corrections) {
    if (correction.category) {
      categories.set(correction.category, (categories.get(correction.category) ?? 0) + 1);
    }
  }
  const topCategory = [...categories.entries()].sort((a, b) => b[1] - a[1])[0]?.[0];

  const empty = (text: string) => (
    <p className="text-[14px] leading-relaxed text-mute">{text}</p>
  );

  const reviewPending = !analysis && spokenTurns > 0;

  const overview = reviewPending ? (
    <ReviewRunner sessionId={session.id} />
  ) : !analysis ? (
    empty("Nothing was said in this one, so there is nothing to review.")
  ) : (
    <div className="flex flex-col gap-6">
      <div className="rounded-2xl border border-line bg-card p-5 sm:p-6">
        {analysis.summary_text && (
          <p className="text-[15px] leading-relaxed">{analysis.summary_text}</p>
        )}
        {analysis.strengths && (
          <p className="mt-4 text-[14px] leading-relaxed text-mute">
            <span className="font-semibold text-ink">Went well: </span>
            {analysis.strengths}
          </p>
        )}
        {fluencyNotes.length > 0 && (
          <ul className="mt-4 flex list-disc flex-col gap-1 pl-5 text-[14px] leading-relaxed text-mute">
            {fluencyNotes.map((note, index) => (
              <li key={index}>{note}</li>
            ))}
          </ul>
        )}
      </div>

      <section>
        <h2 className="text-[17px] font-bold tracking-[-0.015em] sm:text-[21px]">Key Takeaways</h2>
        <div className="mt-3.5 flex flex-col gap-2 sm:mt-4 sm:flex-row sm:gap-5">
          <Takeaway
            icon={<path d="M12 3 L14 9.4 L20.4 11.4 L14 13.4 L12 19.8 L10 13.4 L3.6 11.4 L10 9.4 Z" />}
            title={
              reachedFor.length > 0
                ? `${reachedFor.length} new ${reachedFor.length === 1 ? "word" : "words"} to learn`
                : "No gaps this time"
            }
            body={
              reachedFor.length > 0
                ? "Added to your vocabulary bank, so they'll come up again."
                : "You found the words you needed."
            }
          />
          <Takeaway
            icon={
              <>
                <circle cx="12" cy="12" r="8.8" />
                <path d="M12 7.6 v5" />
                <path d="M12 16.2 v.02" />
              </>
            }
            title={
              corrections.length > 0
                ? `${corrections.length} grammar ${corrections.length === 1 ? "correction" : "corrections"}`
                : "Clean grammar"
            }
            body={topCategory ? `Focus on ${topCategory.toLowerCase()}.` : "Nothing worth flagging this time."}
          />
          <Takeaway
            icon={
              <>
                <circle cx="12" cy="12" r="8.8" />
                <circle cx="12" cy="12" r="3.6" />
              </>
            }
            title="Next time"
            body={analysis.next_steps || "Keep the conversations coming."}
          />
        </div>
      </section>
    </div>
  );

  const used = savedUsed.filter((word) => word.outcome === "used");
  const struggled = savedUsed.filter((word) => word.outcome === "struggled");

  const vocabularyPanel = !analysis ? (
    empty(reviewPending ? "Your vocabulary appears once the review is ready." : "Nothing to show.")
  ) : (
    <div className="flex flex-col gap-9">
      <section>
        <h3 className="text-[17px] font-semibold tracking-[-0.01em]">Words you reached for</h3>
        {reachedFor.length > 0 ? (
          <>
            <p className="mt-1.5 text-[14px] text-mute">
              Added to your{" "}
              <Link href="/vocabulary" className="hover:underline" style={{ color: ACCENT }}>
                vocabulary
              </Link>
              , so they come up again in your next conversations.
            </p>
            <ul className="mt-3 flex flex-col">
              {reachedFor.map((word, index) => (
                <li key={index} className="flex flex-col gap-1 border-b border-line py-3 last:border-0">
                  <div className="flex items-baseline justify-between gap-4">
                    <span className="flex items-center gap-1.5">
                      <span dir={direction} className="text-[16px] font-medium">{word.text}</span>
                      <PronounceButton text={word.text} languageCode={session.target_language} />
                    </span>
                    <span className="text-right text-[14px] text-mute">{word.translation}</span>
                  </div>
                  {word.context && (
                    <span dir="auto" className="text-[13px] text-mute italic">&ldquo;{word.context}&rdquo;</span>
                  )}
                </li>
              ))}
            </ul>
          </>
        ) : (
          <p className="mt-1.5 text-[14px] text-mute">None this time.</p>
        )}
      </section>

      {suggestions.length > 0 && (
        <section>
          <h3 className="text-[17px] font-semibold tracking-[-0.01em]">Worth adding</h3>
          <ul className="mt-3 flex flex-col">
            {suggestions.map((word, index) => (
              <li key={index} className="flex items-center justify-between gap-4 border-b border-line py-3 last:border-0">
                <div className="flex flex-col gap-1">
                  <div className="flex flex-wrap items-baseline gap-x-3">
                    <span className="flex items-center gap-1.5">
                      <span dir={direction} className="text-[16px] font-medium">{word.text}</span>
                      <PronounceButton text={word.text} languageCode={session.target_language} />
                    </span>
                    <span className="text-[14px] text-mute">{word.translation}</span>
                  </div>
                  {word.example && (
                    <span dir={direction} className="text-[13px] text-mute">{word.example}</span>
                  )}
                </div>
                <SaveWordButton
                  sessionId={session.id}
                  word={word}
                  saved={savedWords.has(word.text.trim().toLowerCase())}
                />
              </li>
            ))}
          </ul>
        </section>
      )}

      {(used.length > 0 || struggled.length > 0) && (
        <section>
          <h3 className="text-[17px] font-semibold tracking-[-0.01em]">Your saved words</h3>
          <div className="mt-3 flex flex-wrap gap-2" dir={direction}>
            {used.map((word) => (
              <span key={`used-${word.text}`} className="flex items-center gap-1.5 rounded-full bg-tint px-3 py-1 text-[13px] font-medium text-tint-ink">
                ✓ {word.text}
                <PronounceButton text={word.text} languageCode={session.target_language} size={13} />
              </span>
            ))}
            {struggled.map((word) => (
              <span key={`struggled-${word.text}`} className="flex items-center gap-1.5 rounded-full border border-line px-3 py-1 text-[13px] font-medium text-mute">
                {word.text}
                <PronounceButton text={word.text} languageCode={session.target_language} size={13} />
              </span>
            ))}
          </div>
          {struggled.length > 0 && (
            <p className="mt-3 text-[13px] text-mute">
              Outlined words were tricky this time; they&apos;ll come up again.
            </p>
          )}
        </section>
      )}
    </div>
  );

  const grammarPanel = !analysis ? (
    empty(reviewPending ? "Corrections appear once the review is ready." : "Nothing to show.")
  ) : corrections.length > 0 ? (
    <ul className="flex flex-col gap-4">
      {corrections.map((correction, index) => (
        <li key={index} className="rounded-2xl border border-line bg-card p-5">
          <div className="flex flex-wrap items-center gap-2">
            {correction.category && (
              <span className="text-[11px] font-semibold tracking-wide text-mute uppercase">
                {correction.category}
              </span>
            )}
            {correction.recurring && (
              <span className="rounded-full bg-tint px-2.5 py-0.5 text-[11px] font-semibold text-tint-ink">
                Came up before
              </span>
            )}
          </div>
          <div dir={direction} className="mt-3 flex flex-col gap-1">
            <p className="text-[15px] text-mute line-through decoration-mute/60">{correction.original}</p>
            <p className="flex items-center gap-1.5 text-[16px] font-medium">
              {correction.corrected}
              <PronounceButton text={correction.corrected} languageCode={session.target_language} />
            </p>
          </div>
          {correction.explanation && (
            <p className="mt-3 text-[14px] leading-relaxed text-mute">{correction.explanation}</p>
          )}
        </li>
      ))}
    </ul>
  ) : (
    empty("No grammar slips worth flagging this time.")
  );

  const transcriptPanel =
    transcript.length > 0 ? (
      <div className="flex flex-col gap-4" dir={direction}>
        {transcript.map((turn, index) =>
          turn.role === "agent" ? (
            <div key={index} className="max-w-[85%] self-start rounded-[20px_20px_20px_5px] border border-line bg-card px-4 py-3">
              <p className="text-[15px] leading-relaxed">{turn.text}</p>
              {turn.translation && (
                <p dir="auto" className="mt-1 text-[13px] leading-relaxed text-mute">{turn.translation}</p>
              )}
            </div>
          ) : (
            <div key={index} className="max-w-[85%] self-end rounded-[20px_20px_5px_20px] px-4 py-3 text-white" style={{ background: ACCENT }}>
              <p className="text-[15px] leading-relaxed font-medium">{turn.text}</p>
              {turn.translation && (
                <p dir="auto" className="mt-1 text-[13px] leading-relaxed text-white/85">{turn.translation}</p>
              )}
            </div>
          ),
        )}
      </div>
    ) : (
      empty("Nothing was said in this one.")
    );

  return (
    <main className="flex-1 bg-canvas text-ink">
      <header className="mx-auto flex h-[76px] w-full max-w-[1040px] items-center justify-between px-5 sm:px-10">
        <Link href="/dashboard" aria-label="VOCES home" className="flex items-center gap-2">
          <svg width="26" height="26" viewBox="0 0 48 48" fill={ACCENT} aria-hidden>
            <rect x="0" y="17" width="6" height="14" rx="3" />
            <rect x="10.5" y="9" width="6" height="30" rx="3" />
            <rect x="21" y="0" width="6" height="48" rx="3" />
            <rect x="31.5" y="9" width="6" height="30" rx="3" />
            <rect x="42" y="17.5" width="6" height="13" rx="3" />
          </svg>
          <span className="text-[19px] font-extrabold tracking-[0.05em]" style={{ color: ACCENT }}>VOCES</span>
        </Link>
        <div className="flex items-center gap-3">
          <Link
            href="/conversation/new"
            className="rounded-full px-4 py-2 text-[13px] font-semibold text-white"
            style={{ background: ACCENT }}
          >
            New conversation
          </Link>
          <Link
            href="/dashboard"
            aria-label="Close summary"
            className="grid size-10 place-items-center rounded-full border border-line bg-card transition-colors hover:border-[#DE5E1C]/50"
          >
            <svg width="15" height="15" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" className="text-mute" aria-hidden>
              <path d="M2.4 2.4 L11.6 11.6" />
              <path d="M11.6 2.4 L2.4 11.6" />
            </svg>
          </Link>
        </div>
      </header>

      <div className="mx-auto flex w-full max-w-[1040px] flex-col gap-5 px-5 pt-3 pb-24 sm:gap-7 sm:px-10 sm:pt-8">
        <div className="flex items-start gap-3.5 sm:items-center sm:gap-5">
          <span className="grid size-[52px] shrink-0 place-items-center rounded-full bg-[#EB6720] sm:size-16">
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
              <path d="M4.6 12.6 L9.6 17.4 L19.4 7" />
            </svg>
          </span>
          <div className="flex-1 pt-0.5">
            <h1 className="text-[22px] font-bold tracking-[-0.02em] sm:text-[34px]">
              {spokenTurns > 0 ? "Session Complete" : "That one stayed quiet"}
            </h1>
            <p className="mt-1 text-[13.5px] text-mute sm:mt-2 sm:text-base">
              {spokenTurns > 0
                ? "Great job! Here's your session summary."
                : "Nothing was said, so there's no review this time."}
            </p>
          </div>
          {spokenTurns > 0 && (
            <a
              href="#report"
              className="hidden h-[54px] shrink-0 items-center gap-2.5 rounded-full px-7 text-base font-semibold text-white shadow-[0_12px_26px_rgba(160,64,14,0.22)] sm:flex"
              style={{ background: ACCENT }}
            >
              View Full Report
              <svg width="15" height="12" viewBox="0 0 18 14" fill="none" stroke="#FFFFFF" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
                <path d="M1 7 h15" />
                <path d="M10.4 1.4 L16 7 l-5.6 5.6" />
              </svg>
            </a>
          )}
        </div>

        <div className="flex flex-col gap-3 rounded-2xl border border-line bg-card p-3.5 sm:rounded-[18px] sm:p-5">
          <div className="flex items-center gap-3.5 sm:gap-[18px]">
            <SessionThumb code={session.target_language} />
            <div className="flex flex-col gap-1.5">
              <span className="text-base font-semibold tracking-[-0.01em] sm:text-xl">
                {scenarioLabel(session.scenario) ?? "Free conversation"}
              </span>
              <span className="text-[13px] text-mute sm:text-[14.5px]">
                {minutes ? `${minutes} min · ` : ""}
                {language}
              </span>
            </div>
          </div>
          <RecordingSection
            sessionId={session.id}
            hasRecording={Boolean(session.agent_session_id)}
          />
        </div>

        {spokenTurns > 0 && (
          <div className="flex gap-2 sm:gap-5">
            <ScoreCard title="Speaking" caption="Your share of the talk">
              <Ring percent={speakingShare} label={`${speakingShare}%`} color="#2F8A3C" track="#DCEEDC" />
            </ScoreCard>
            <ScoreCard title="Grammar" caption="Sentences without a slip">
              <Ring
                percent={grammarScore}
                label={grammarScore === null ? "…" : `${grammarScore}%`}
                color="#3179F0"
                track="#DCE8FB"
              />
            </ScoreCard>
            <ScoreCard title="Vocabulary" caption="New words to learn">
              <Ring
                percent={analysis ? 100 : null}
                label={analysis ? String(reachedFor.length) : "…"}
                color="#6E3FDE"
                track="#E4DCFA"
              />
            </ScoreCard>
          </div>
        )}

        <ReportTabs
          tabs={[
            { id: "overview", label: "Overview", content: overview },
            { id: "vocabulary", label: "Vocabulary", content: vocabularyPanel },
            { id: "grammar", label: "Grammar", content: grammarPanel },
            { id: "transcript", label: "Transcript", content: transcriptPanel },
          ]}
        />
      </div>
    </main>
  );
}
